### ISSUE TITLE
При обновлении стартовой страницы интерфейс мигает.

### ISSUE THREAD

**Issue by dustyo-O** [HavingNoFuture/js-browser-netology-diploma#2]
https://monosnap.com/file/XTeLlbiU7RiXbS5jaCXuF0R0rDAAe7
Это от того, что изначально меню находится в неверном состоянии, и ты его переключаешь jsом. Просто внеси правки в html/css

**Comment by HavingNoFuture** [comment]
Не уверен, что решил. Попробовал оставить в меню начальное состояние(которое при первой запуске приложения(only new)) + Переделал функцию переключения меню(добавил в нее запоминание мода в session).

**Comment by dustyo-O** [comment]
ну если не воспроизводится, закрывай
