### ISSUE TITLE
Разваливается меню у правого края

### ISSUE THREAD

**Issue by dustyo-O** [HavingNoFuture/js-browser-netology-diploma#3]
Собрал несколько кейсов
https://monosnap.com/file/gjjgYheJgwokd1OrbsbTCqXVXF5vtI
https://monosnap.com/file/cc76wAbHdL0r1K2s9wLjQfMRiNr2ig

Ожидается, что меню не будет разваливаться, и будет "отскакивать" от правого края, чтобы всегда быть внутри окна браузера

**Comment by HavingNoFuture** [comment]
Добавил проверку в tick(). Если сломалась - отскакивает. Есть еще вариант "постепенно" возвращать в нормальное состояние - закоментил в checkBadMenu().

**Comment by dustyo-O** [comment]
нужно сделать так, чтобы никогда не ломалось, это ж некрасиво когда ломается. Немного css поможет
