### ISSUE TITLE
Закрытие формы без комментариев не удаляет метку

### ISSUE THREAD

**Issue by dustyo-O** [HavingNoFuture/js-browser-netology-diploma#5]
Ожидается, что если мы ждем кнопку закрыть в форме комментариев, в которой нет отправленных комментов, пропадет и форма, и метка

**Comment by HavingNoFuture** [comment]
При клике на Закрыть добавил проверку: Если не найдет коммент боди (отсутствует тело комментария) -> Удаляет форму. Иначе просто закрывает тело формы.
