### ISSUE TITLE
Двустрочный комментарий собирается в однострочный

### ISSUE THREAD

**Issue by dustyo-O** [HavingNoFuture/js-browser-netology-diploma#6]
Отправляю

```
лол
корвалол
```

получаю

`лол корвалол`

ожидается, что перенос строки сохранится после отправки

**Comment by HavingNoFuture** [comment]
Использую encodeURIComponent(), чтобы привести комментарий в удобную для запроса форму. Пока ничего не придумал как это поправил. Можно наводку?)

**Comment by dustyo-O** [comment]
два пути - или использовать display, в котором переносы строк сохраняются, или заменять символ переноса строки на соответствующий тег

**Comment by HavingNoFuture** [comment]
Решил изящнее: Добавил в css: white-space: pre для поля отображения коммента. Вроде норм)
